# [START runtime]
service: channelpay-dashboard-portal
runtime: python27
threadsafe: yes
api_version: 1
# [END runtime]

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|otf|eot|svg|ttf|woff|woff2)(|\.map))$
    static_files: build/\1
    upload: build/(.*)(|\.map)
    secure: always

  - url: /(.*)
    static_files: build/index.html
    upload: build/index.html
    secure: always

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
  - ^node_modules$
  - ^app\.yaml
  - ^README\..*
  - \.gitignore
  - ^\.git$
  - ^grunt\.js
  - ^src$
  - ^e2e$
  - \.editorconfig
  - ^karma\.config\.js
  - ^package\.json
  - ^protractor\.conf\.js
  - ^tslint\.json
